replicaCount: 2

image:
  repository: 002369670798.dkr.ecr.ap-south-1.amazonaws.com/gitops-app
  tag: fa0c15f
  pullPolicy: Always

imagePullSecrets:
  - name: ecr-secret

container:
  port: 8080

service:
  name: gitops-service
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  name: gitops-app-ingress
  className: alb
  scheme: internet-facing
  targetType: ip
  subnets: "subnet-02a6d6caea53ca8c3,subnet-002fe003aab1aca96"
  path: /
  pathType: Prefix
